# Load in Numpy

In [1]:
import numpy as np

## The Basics

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [13]:
# Get Dimension
a.ndim

# Get Shape
b.shape

# Get type
a.dtype

# Get Size
a.itemsize

# Get total size
a.nbytes 

12

## Acessing/Changing specific elements, rows, columns, etc

In [14]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [16]:
# Get a specific element [row, column]
a[1,5]

13

In [18]:
# Get a specific row 
a[0]
# or
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
# Get a specific column 
a[:,2]

array([ 3, 10])

In [23]:
# Getting a little more fancy  [ startindex : endindex : stepsize] # [largura, altura, profundidade ]
a[0,1:6:2] 

array([2, 4, 6])

In [24]:
# Changing elements
# 1º acessa os elementos que quer trocar
# 2º = adiciona elemento
a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

3Dimensional example

In [26]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [27]:
# Get specicif element (work outside in)
b[0,1,1]

4

In [28]:
# Replace
b[:,1,:] =[[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

## Initializing Different Types of Arrays

In [32]:
# All 0s matrix
np.zeros([2,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [33]:
# All 1s matrix
np.ones([4,2,2], dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [34]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [35]:
# Random decimal numbers
np.random.rand(4,2,3) 

array([[[0.18182536, 0.31957392, 0.69330334],
        [0.78785336, 0.99785795, 0.29749637]],

       [[0.2835031 , 0.83878178, 0.83017137],
        [0.55501902, 0.38580668, 0.58678603]],

       [[0.29266108, 0.50375809, 0.97607259],
        [0.39854976, 0.68079734, 0.17828691]],

       [[0.47066455, 0.16215327, 0.0609196 ],
        [0.82413691, 0.18870168, 0.65517966]]])

In [59]:
# Random Integer Values
np.random.randint(3,4,4) 
np.random.randint(2, size=(10,10)
np.random.randint(2, size=10)

array([1, 1, 0, 0, 0, 1, 1, 0, 1, 0])

In [112]:
# Repeat an array 
array1 = np.array([1,2,3]) # if you put more [] 
array_repeat = np.repeat(array1,3)  # (array to repeat, number of times, )
array_repeat

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [113]:
# Repeat an array and put in 2-dimensional 
array1 = np.array([[1,2,3]]) # put two [] to make 2-dimensional
array_repeat = np.repeat(array1,3, axis=0) # 0 axis make the rows ## if axis=1 it will be like before array([1, 1, 1, 2, 2, 2, 3, 3, 3])
array_repeat

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [103]:
# Exercise: Create this array
#[[1. 1. 1. 1. 1.]
# [1. 0. 0. 0. 1.]
# [1. 0. 9. 0. 1.]
# [1. 0. 0. 0. 1.]
# [1. 1. 1. 1. 1.]]

In [78]:
exercise = np.ones([5,5])
exercise

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [104]:
exercise[1,1:4] = 0
exercise[2,1] = 0
exercise[2,2] = 9
exercise[2,3] = 0
exercise[3,1:4] = 0
print(exercise)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [108]:
# A better resolution
array1 = np.ones([5,5])
array1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [109]:
array2 = np.zeros([3,3])
array2[1,1] = 9
array2

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [110]:
array1[1:4 , 1:4] = array2
print(array1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### BE AWARE when copying arrays

array1 = array2 IT'S NOT A COPY (igualdade) 

In [114]:
a = np.array([1,2,3])
b = a.copy()
b                # you can change a or b and it won't do the change in both arrays

array([1, 2, 3])

## Mathematics

In [115]:
a = np.array([1,2,3,4])
a + 2

array([3, 4, 5, 6])

In [116]:
a - 2

array([-1,  0,  1,  2])

In [117]:
a * 2

array([2, 4, 6, 8])

In [118]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [119]:
a // 2

array([0, 1, 1, 2], dtype=int32)

In [120]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [121]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

### Linear Algebra

In [129]:
# Remember in linear algebra you need to have the columns of the first matrix be equal to the rows of the second ones

a = np.ones([2,3])
print(a)

b = np.full([3,2], 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [131]:
np.matmul(a,b)   # Matrix product of two arrays

array([[6., 6.],
       [6., 6.]])

In [133]:
# Find the determinant 
c = np.identity(3)
np.linalg.det(c)

1.0

## Statistics !

In [135]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [156]:
# When axis is present it returns all values
np.min(stats, axis=0) # (axis=0) = min of the first COLUMNS and min of the second COLUMNS

array([1, 2, 3])

In [151]:
np.min(stats, axis=1) # (axis=1) = min of the first ROWS and min of the second ROWS

array([1, 4])

In [162]:
# min just one value
np.min(stats)

1

In [183]:
# mean
stats.mean()
np.mean(stats)
print(np.mean(stats))

# median
print(np.median(stats))

# std
print(np.std(stats))

3.5
3.5
1.707825127659933


### Reorganizing arrays

In [186]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape(8,1)  # (rows, columns)
print(after)

after2 = before.reshape(4,2)
print(after2)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [193]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])  # I can do np.vstack([v1,v2,v2,v2])
display(v1)
display(v2)
np.vstack([v1,v2])

# Horizontal stacking is the same principle
# np.hstack

array([1, 2, 3, 4])

array([5, 6, 7, 8])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Miscellaneous

#### Load Data From File

In [199]:
filedata = np.genfromtxt('data_test.txt', delimiter=',')
display(filedata)   # float

# Integer
display(filedata.astype('int32'))  # just display like that

# To really change to a integer
filedata = filedata.astype('int32')  # make a copy (matching)
filedata

array([[  1.,   1.,   2.,   2.,   3.,   3.,   3.,   3.,   5.,   5.,  45.,
         43.],
       [  3.,  45.,  56.,   5.,   6., 565.,  56.,  65.,  65.,   1.,   2.,
          3.],
       [  6.,   6.,   3.,   3.,  36.,  46.,   6.,   3., 656.,   3.,   6.,
          1.]])

array([[  1,   1,   2,   2,   3,   3,   3,   3,   5,   5,  45,  43],
       [  3,  45,  56,   5,   6, 565,  56,  65,  65,   1,   2,   3],
       [  6,   6,   3,   3,  36,  46,   6,   3, 656,   3,   6,   1]])

array([[  1,   1,   2,   2,   3,   3,   3,   3,   5,   5,  45,  43],
       [  3,  45,  56,   5,   6, 565,  56,  65,  65,   1,   2,   3],
       [  6,   6,   3,   3,  36,  46,   6,   3, 656,   3,   6,   1]])

### Boolean Masking and Advanced Index

In [228]:
### and & 
### or |
### not ~
### is ==
### not is !=

In [200]:
filedata > 50

array([[False, False, False, False, False, False, False, False, False,
        False, False, False],
       [False, False,  True, False, False,  True,  True,  True,  True,
        False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False]])

In [201]:
 # Index based on a MASK
filedata[filedata > 50] # By doing this you grab only the values that actually have a value > 50

array([ 56, 565,  56,  65,  65, 656])

In [202]:
# You can also index with  a list in NumPY
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]] # positions

array([2, 3, 9])

In [224]:
display(filedata)
np.any(filedata > 50, axis=0) # np.any create an array  # axis=0 COLUMNS

array([[  1,   1,   2,   2,   3,   3,   3,   3,   5,   5,  45,  43],
       [  3,  45,  56,   5,   6, 565,  56,  65,  65,   1,   2,   3],
       [  6,   6,   3,   3,  36,  46,   6,   3, 656,   3,   6,   1]])

array([False, False,  True, False, False,  True,  True,  True,  True,
       False, False, False])

In [222]:
np.all(filedata > 50)

False

In [226]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False, False, False, False, False,
        False, False, False],
       [False, False,  True, False, False, False,  True,  True,  True,
        False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False]])

In [227]:
~((filedata > 50) & (filedata < 100))  # ~ means NOT

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True, False,  True,  True,  True, False, False, False,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True]])